<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'HTML_To_Markdown' => $vendorDir . '/nickcernis/html-to-markdown/HTML_To_Markdown.php',
    'Smarty' => $vendorDir . '/smarty/smarty/distribution/libs/Smarty.class.php',
    'SmartyBC' => $vendorDir . '/smarty/smarty/distribution/libs/SmartyBC.class.php',
    'SmartyCompilerException' => $vendorDir . '/smarty/smarty/distribution/libs/Smarty.class.php',
    'SmartyException' => $vendorDir . '/smarty/smarty/distribution/libs/Smarty.class.php',
    'Smarty_Security' => $vendorDir . '/smarty/smarty/distribution/libs/sysplugins/smarty_security.php',
);
