<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-03-31 07:13

$extensionPath = t3lib_extMgm::extPath('smarty');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_smarty' => $extensionClassesPath . 'Backport/class.tx_smarty.php',
	'tx_smarty_cacheresources_memcache' => $extensionClassesPath . 'CacheResources/Memcache.php',
	'tx_smarty_cacheresources_mysql' => $extensionClassesPath . 'CacheResources/Mysql.php',
	'tx_smarty_cacheresources_redis' => $extensionClassesPath . 'CacheResources/Redis.php',
	'tx_smarty_caching_tags' => $extensionClassesPath . 'CacheResources/Tags.php',
	'tx_smarty_core_configuration' => $extensionClassesPath . 'Core/Configuration.php',
	'tx_smarty_core_frontendproxy' => $extensionClassesPath . 'Core/FrontendProxy.php',
	'tx_smarty_core_wrapper' => $extensionClassesPath . 'Core/Wrapper.php',
	'tx_smarty_exception_cacheexception' => $extensionClassesPath . 'Exception/CacheException.php',
	'tx_smarty_exception_coreexception' => $extensionClassesPath . 'Exception/CoreException.php',
	'tx_smarty_exception_pluginexception' => $extensionClassesPath . 'Exception/PluginException.php',
	'tx_smarty_hooks_clearcache' => $extensionClassesPath . 'Hooks/ClearCache.php',
	'tx_smarty_service_compatibility' => $extensionClassesPath . 'Service/Compatility.php',
	'tx_smarty_service_smarty' => $extensionClassesPath . 'Service/Smarty.php',
	'tx_smarty_sysplugins_dotnotationfilter' => $extensionClassesPath . 'SysPlugins/DotNotationFilter.php',
	'tx_smarty_sysplugins_extresource' => $extensionClassesPath . 'SysPlugins/ExtResource.php',
	'tx_smarty_sysplugins_pathresource' => $extensionClassesPath . 'SysPlugins/PathResource.php',
	'tx_smarty_utility_array' => $extensionClassesPath . 'Utility/Array.php',
	'tx_smarty_utility_environment' => $extensionClassesPath . 'Utility/Environment.php',
	'tx_smarty_utility_extconf' => $extensionClassesPath . 'Utility/ExtConf.php',
	'tx_smarty_utility_path' => $extensionClassesPath . 'Utility/Path.php',
	'tx_smarty_utility_scalar' => $extensionClassesPath . 'Utility/Scalar.php',
	'tx_smarty_utility_typo3' => $extensionClassesPath . 'Utility/Typo3.php',
	'tx_smarty_utility_typoscript' => $extensionClassesPath . 'Utility/TypoScript.php',
);
?>