<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-01-27 12:32

$extensionPath = t3lib_extMgm::extPath('smarty');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_smarty' => $extensionClassesPath . 'Backport/class.tx_smarty.php',
	'tx_smarty_core_cobjectproxy' => $extensionClassesPath . 'Core/CobjectProxy.php',
	'tx_smarty_core_configuration' => $extensionClassesPath . 'Core/Configuration.php',
	'tx_smarty_core_wrapper' => $extensionClassesPath . 'Core/Wrapper.php',
	'tx_smarty_exception_coreexception' => $extensionClassesPath . 'Exception/CoreException.php',
	'tx_smarty_exception_pluginexception' => $extensionClassesPath . 'Exception/PluginException.php',
	'tx_smarty_factory' => $extensionClassesPath . 'Factory.php',
	'tx_smarty_hooks_clearcache' => $extensionClassesPath . 'Hooks/ClearCache.php',
	'tx_smarty_sysplugins_dotnotationfilter' => $extensionClassesPath . 'SysPlugins/DotNotationFilter.php',
	'tx_smarty_sysplugins_extresource' => $extensionClassesPath . 'SysPlugins/ExtResource.php',
	'tx_smarty_sysplugins_pathresource' => $extensionClassesPath . 'SysPlugins/PathResource.php',
	'tx_smarty_tests_unit_facade_configurationtest' => $extensionPath . 'Tests/Unit/Facade/ConfigurationTest.php',
	'tx_smarty_utility_array' => $extensionClassesPath . 'Utility/Array.php',
	'tx_smarty_utility_environment' => $extensionClassesPath . 'Utility/Environment.php',
	'tx_smarty_utility_extconf' => $extensionClassesPath . 'Utility/ExtConf.php',
	'tx_smarty_utility_path' => $extensionClassesPath . 'Utility/Path.php',
	'tx_smarty_utility_scalar' => $extensionClassesPath . 'Utility/Scalar.php',
	'tx_smarty_utility_smarty' => $extensionClassesPath . 'Utility/Smarty.php',
	'tx_smarty_utility_typo3' => $extensionClassesPath . 'Utility/Typo3.php',
	'tx_smarty_utility_typoscript' => $extensionClassesPath . 'Utility/TypoScript.php',
);
?>