<?php
/***************************************************************
 *  Copyright notice
 *
 *  (c) 2011 Simon Tuck <stu@rtp.ch>
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

class Tx_Smarty_Core_Wrapper
    extends SmartyBC
{
    /**
     * @var Tx_Smarty_Core_Configuration
     */
    private $configuration;

    /**
     * Language file(s) for the translate view helper
     *
     * @var string|array
     */
    private $language_file;

    /**
     * @var boolean
     */
    private $mute_errors = false;

    /**
     * @var boolean
     */
    private $respect_no_cache = false;

    /**
     * Gets the instance of the configuration manager
     *
     * @return Tx_Smarty_Core_Configuration
     */
    public function getConfiguration()
    {
        if (is_null($this->configuration)) {
            $this->configuration = t3lib_div::makeInstance('Tx_Smarty_Core_Configuration', $this);
        }

        return $this->configuration;
    }


    /************************************************************************
     * Peg smarty's cache setting to TSFE->no_cache
     ************************************************************************/

    /**
     * @param $respectNoCache
     */
    public function setRespectNoCache($respectNoCache = false)
    {
        $this->respect_no_cache = (boolean) $respectNoCache;
    }

    /**
     * @return bool
     */
    public function getRespectNoCache()
    {
        return $this->respect_no_cache;
    }


    /************************************************************************
     * Mutes expected warnings and notices deliberately generated by Smarty
     ************************************************************************/

    /**
     * Mute/unmute errors
     *
     * @see http://www.smarty.net/docs/en/api.mute.expected.errors.tpl
     * @param $muteErrors
     */
    public function setMuteErrors($muteErrors = false)
    {
        $this->mute_errors = (boolean) $muteErrors;

        if ($this->mute_errors) {
            $this->muteExpectedErrors();

        } else {
            $this->unmuteExpectedErrors();
        }
    }

    /**
     * Get Mute errors setting
     *
     * @return array|bool
     */
    public function getMuteErrors()
    {
        return $this->mute_errors;
    }


    /************************************************************************
     * Resolves and sets/gets language file property
     ************************************************************************/

    /**
     * Sets language file(s)
     *
     * @param $languageFile
     */
    public function setLanguageFile($languageFile)
    {
        $this->addLanguageFile($languageFile);
    }

    /**
     * Gets language file(s)
     *
     * @param null $index
     * @return array|null
     */
    public function getLanguageFile($index = null)
    {
        if ($index !== null) {
            return isset($this->language_file[$index]) ? $this->language_file[$index] : null;
        }

        return (array) $this->language_file;
    }

    /**
     * Adds language file(s)
     *
     * @param $languageFile
     * @param null $key
     * @return Tx_Smarty_Core_Wrapper
     */
    public function addLanguageFile($languageFile, $key = null)
    {
        // make sure we're dealing with an array
        $this->language_file = (array) $this->language_file;

        if (is_array($languageFile)) {
            foreach ($languageFile as $k => $v) {
                if (is_int($k)) {
                    // indexes are not merged but appended
                    $this->language_file[] = $v;

                } else {
                    // string indexes are overridden
                    $this->language_file[$k] = $v;
                }
            }
        } elseif (!is_null($key)) {
            $this->language_file[$key] = $languageFile;

        } else {
            $this->language_file[] = $languageFile;
        }

        $this->language_file = array_unique($this->language_file);

        return $this;
    }


    /************************************************************************
     * Resolve directories/paths in "dir" properties
     ************************************************************************/

    /**
     * Set template directory
     *
     * @param array|string $templateDir
     * @return Smarty
     */
    public function setTemplateDir($templateDir)
    {
        $templateDir = Tx_Smarty_Utility_Path::resolvePaths($templateDir);
        return parent::setTemplateDir($templateDir);
    }

    /**
     * Add template directory(s)
     *
     * @param array|string $templateDir
     * @param null $key
     * @return Smarty
     */
    public function addTemplateDir($templateDir, $key = null)
    {
        $templateDir = Tx_Smarty_Utility_Path::resolvePaths($templateDir);
        return parent::addTemplateDir($templateDir, $key);
    }

    /**
     * Set config directory
     *
     * @param $config_dir
     * @return Smarty
     */
    public function setConfigDir($config_dir)
    {
        $config_dir = Tx_Smarty_Utility_Path::resolvePaths($config_dir);
        return parent::setConfigDir($config_dir);
    }

    /**
     * Add config directory(s)
     *
     * @param array|string $config_dir
     * @param null $key
     * @return Smarty
     */
    public function addConfigDir($config_dir, $key = null)
    {
        $config_dir = Tx_Smarty_Utility_Path::resolvePaths($config_dir);
        return parent::addConfigDir($config_dir, $key);
    }

    /**
     * Set plugins directory
     *
     * @param array|string $plugins_dir
     * @return Smarty
     */
    public function setPluginsDir($plugins_dir)
    {
        $plugins_dir = Tx_Smarty_Utility_Path::resolvePaths($plugins_dir);
        // Never overwrite plugins_dir! Always translate the plugins_dir setter to an adder.
        return parent::addPluginsDir($plugins_dir);
    }

    /**
     * @param $plugins_dir
     * @return Smarty
     */
    public function addPluginsDir($plugins_dir)
    {
        $plugins_dir = Tx_Smarty_Utility_Path::resolvePaths($plugins_dir);
        return parent::addPluginsDir($plugins_dir);
    }

    /**
     * Set compile directory
     *
     * @param string $compile_dir
     * @return Smarty
     */
    public function setCompileDir($compile_dir)
    {
        $compile_dir = Tx_Smarty_Utility_Path::resolvePaths($compile_dir);
        return parent::setCompileDir($compile_dir);
    }

    /**
     * Set cache directory
     *
     * @param string $cache_dir
     * @return Smarty
     */
    public function setCacheDir($cache_dir)
    {
        $cache_dir = Tx_Smarty_Utility_Path::resolvePaths($cache_dir);
        return parent::setCacheDir($cache_dir);
    }

    /**
     * Set the debug template
     *
     * @param string $tpl_name
     * @return Smarty
     */
    public function setDebugTemplate($tpl_name)
    {
        $tpl_name = Tx_Smarty_Utility_Path::resolvePaths($tpl_name);
        return parent::setDebugTemplate($tpl_name);
    }


    /************************************************************************
     * Modified display
     ************************************************************************/

    /**
     * returns a rendered Smarty template: Modifies the display method to fetch the rendered
     * template instead of displaying it.
     *
     * @param string $template   the resource handle of the template file or template object
     * @param mixed  $cache_id   cache id to be used with this template
     * @param mixed  $compile_id compile id to be used with this template
     * @param object $parent     next higher level of Smarty variables
     * @return string|void       rendered template
     */
    public function display($template = null, $cache_id = null, $compile_id = null, $parent = null)
    {
        // Disables caching if it is globally disabled or has been pegged to TSFE->no_cache
        if (($this->respect_no_cache === true && isset($GLOBALS['TSFE']->no_cache) && $GLOBALS['TSFE']->no_cache)
            || (boolean) Tx_Smarty_Utility_ExtConf::getExtConfValue('disable_caching')) {

            $this->set('caching', false);
        }

        return $this->fetch($template, $cache_id, $compile_id, $parent, false);
    }


    /************************************************************************
     * Accessors
     ************************************************************************/

    /**
     * @param $property
     * @return mixed
     */
    final public function get($property)
    {
        return call_user_func(array($this->getConfiguration(), 'get'), $property);
    }

    /**
     * @param string $property
     * @return array|mixed|null|string
     */
    public function __get($property)
    {
        if ($property === 'template_dir' ||
            $property === 'path_to_template_directory') {

            return $this->getTemplateDir();

        } elseif ($property === 'plugins_dir') {
            return $this->getPluginsDir();

        } elseif ($property === 'config_dir') {
            return $this->getConfigDir();

        } elseif ($property === 'compile_dir') {
            return $this->getCompileDir();

        } elseif ($property === 'cache_dir') {
            return $this->getCacheDir();

        } elseif ($property === 't3_languageFile' ||
                  $property === 'path_to_language_file' ||
                  $property === 'relPathToLanguageFile') {

            return $this->getLanguageFile($property);

        } elseif ($property === 'respect_no_cache') {
            return $this->getRespectNoCache();

        } elseif ($property === 't3_extVars' ||
                  $property === 'pObj' ||
                  $property === 'cObj' ||
                  $property === 't3_confVars' ||
                  $property === 't3_smartyVars' ||
                  $property === 't3_conf' ||
                  $property === '_debug_resource') {

            t3lib_div::logDeprecatedFunction();
            return null;

        } else {
            return $this->get($property);
        }
    }

    /**
     * @param $property
     * @param $value
     * @return mixed
     */
    final public function add($property, $value)
    {
        return call_user_func(array($this->getConfiguration(), 'add'), $property, $value);
    }

    /**
     * @param $property
     * @param $value
     * @return mixed
     */
    final public function set($property, $value)
    {
        return call_user_func(array($this->getConfiguration(), 'set'), $property, $value);
    }

    /**
     * Generic setter for properties which are either deprecated or not accessible (i.e. private and therefore have
     * to be translated to the appropriate setter method).
     *
     * @param string $property
     * @param mixed $value
     */
    public function __set($property, $value)
    {
        if ($property === 'template_dir' ||
            $property === 'path_to_template_directory') {

            $this->setTemplateDir($value);

        } elseif ($property === 'plugins_dir') {
            $this->addPluginsDir($value);

        } elseif ($property === 'config_dir') {
            $this->setConfigDir($value);

        } elseif ($property === 'compile_dir') {
            $this->setCompileDir($value);

        } elseif ($property === 'cache_dir') {
            $this->setCacheDir($value);

        } elseif ($property === 't3_languageFile' ||
                  $property === 'path_to_language_file' ||
                  $property === 'relPathToLanguageFile') {

            $this->setLanguageFile($value);

        } elseif ($property === 'respect_no_cache') {
            $this->setRespectNoCache($value);

        } elseif ($property === 't3_extVars' ||
                  $property === 'pObj' ||
                  $property === 'cObj' ||
                  $property === 't3_confVars' ||
                  $property === 't3_smartyVars' ||
                  $property === 't3_conf' ||
                  $property === '_debug_resource') {

            t3lib_div::logDeprecatedFunction();

        } else {
            $this->set($property, $value);
        }
    }


    /************************************************************************
     * Deprecated methods
     ************************************************************************/

    /**
     * Sets the template directory
     *
     * @param $path_to_template_directory
     * @deprecated Use setTemplateDir() instead
     */
    public function setPathToTemplateDirectory($path_to_template_directory)
    {
        t3lib_div::logDeprecatedFunction();
        $this->setTemplateDir($path_to_template_directory);
    }

    /**
     * Gets the template directory
     *
     * @return array|null
     * @deprecated Use setTemplateDir() instead
     */
    public function getPathToTemplateDirectory()
    {
        t3lib_div::logDeprecatedFunction();
        return $this->getTemplateDir();
    }

    /**
     * Set the language file
     *
     * @param $path_to_language_file
     * @deprecated use setLanguageFile() instead
     */
    public function setRelPathToLanguageFile($path_to_language_file)
    {
        t3lib_div::logDeprecatedFunction();
        $this->setLanguageFile($path_to_language_file);
    }

    /**
     * Get the language file(s)
     *
     * @return array|null
     * @deprecated use getLanguageFile() instead
     */
    public function getRelPathToLanguageFile()
    {
        t3lib_div::logDeprecatedFunction();
        return $this->getLanguageFile();
    }

    /**
     * Set the language file
     *
     * @param $path_to_language_file
     * @deprecated use setLanguageFile() instead
     */
    public function setPathToLanguageFile($path_to_language_file)
    {
        t3lib_div::logDeprecatedFunction();
        $this->setLanguageFile($path_to_language_file);
    }

    /**
     * Get the language file(s)
     *
     * @return array|null
     * @deprecated use getLanguageFile() instead
     */
    public function getPathToLanguageFile()
    {
        t3lib_div::logDeprecatedFunction();
        return $this->getLanguageFile();
    }

    /**
     * Set smarty configuration variable
     *
     * @param $property
     * @param $value
     * @deprecated use accessors instead. For example setCacheLifetime(3600)
     */
    public function setSmartyVar($property, $value)
    {
        t3lib_div::logDeprecatedFunction();
        $this->set($property, $value);
    }
}